# Development

# Specify a base image
FROM node:alpine

WORKDIR /app

# Install dependencies
COPY ./package.json ./
RUN npm install
COPY ./ ./

CMD ["npm", "run", "start"]

# docker build -f Dockerfile.dev .
# docker run -p 3000:3000 -v @echo %cd%:/app bd7fc7bbfc03
# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app bd7fc7bbfc03
# docker run -p 3000:3000 -v /app/node_modules -v D:\Code\Docker\swag\frontend:/app bd7fc7bbfc0